/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

import DAO.DoanhThuDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ADMIN
 */
public class DoanhThu extends javax.swing.JPanel {
DefaultTableModel tablemodel = new DefaultTableModel();
    /** Creates new form DoanhThu */
    public DoanhThu() {
        initComponents();
    }

    public void initTable() {
        String[] cols = new String[]{"Mã Doanh Thu", "Mã Hóa Đơn", "Tổng tiền"};
        
        tablemodel.setColumnIdentifiers(cols);
        jTable1DoanhThu.setModel(tablemodel);
    }

    public void fillTable() {
        tablemodel.setRowCount(0);
        int tongDoanhThu = 0;
        DoanhThuDAO dtDao = new DoanhThuDAO();

        try {
            for (model.DoanhThu dt : dtDao.getAll()) {
                tablemodel.addRow(new Object[]{
                    dt.getMaDT(),
                    dt.getMaHD(),
                    String.format("%,d VNĐ", dt.getTongTien())
                });
                tongDoanhThu += dt.getTongTien();
            }

            // Hiển thị tổng doanh thu
            jLabel2.setText(String.format("%,d VNĐ", tongDoanhThu));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTongDoanhThu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1DoanhThu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Doanh Thu");

        jLabelTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTongDoanhThu.setText("Tổng Doanh Thu: ");

        jTable1DoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1DoanhThu);

        jLabel2.setText("_");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabelTongDoanhThu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTongDoanhThu)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTongDoanhThu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1DoanhThu;
    // End of variables declaration//GEN-END:variables

}
