package view;

import DAO.HoaDonDAO;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class QLHD extends javax.swing.JPanel {

    /**
     * Creates new form QLDH
     */
   DefaultTableModel tableModel;
    HoaDonDAO hdDao = new HoaDonDAO();
    /**
     * Creates new form QLHD
     */
    public QLHD() {
        initComponents();
        initTable();
        fillTable();
    }
 
    public void initTable() {
        String[] cols = new String[]{"Mã HĐ", "Mã NV", "Ngày đặt", "Giá tiền", "Mã KH"};
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(cols);
        TBdonHang.setModel(tableModel);
    }

    public void fillTable() {
        tableModel.setRowCount(0);
        for (HoaDon hd : hdDao.getAll()) {
            tableModel.addRow(hdDao.getRow(hd));
        }
    }
    
 private boolean validateForm() {
    if (TXTmaHD.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã hóa đơn.");
        return false;
    }
    if (TXTmaNV.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên.");
        return false;
    }
    if (TXTngayDat.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày đặt.");
        return false;
    }
    if (TXTgia.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập giá tiền.");
        return false;
    }
    try {
        double gia = Double.parseDouble(TXTgia.getText().trim());
        if (gia <= 0) {
            JOptionPane.showMessageDialog(this, "Giá tiền phải lớn hơn 0.");
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá tiền phải là số hợp lệ.");
        return false;
    }
    if (TXTmaKH.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng.");
        return false;
    }
    return true;
}
 
  public void add(){
        int maSP = Integer.parseInt(TXTmaHD.getText());
        int tenSP = Integer.parseInt(TXTmaNV.getText());
        Date ngaydathang = Date.valueOf(TXTngayDat.getText());
        double giatien = Double.parseDouble(TXTgia.getText());
        int maKH = Integer.valueOf(TXTmaKH.getText());
        HoaDon hd = new HoaDon(maSP,tenSP,giatien,ngaydathang,maKH);
        if (hdDao.addHD(hd)==1) {
            fillTable();
            JOptionPane.showMessageDialog(this, "Nhap thanh cong");
        }else{
            JOptionPane.showMessageDialog(this, "Loi!");
        }
        
    }
    
    public void Update() {
        int i = TBdonHang.getSelectedRow();
        if (i != -1) {          
         int maSP = Integer.parseInt(TXTmaHD.getText());
        int tenSP = Integer.parseInt(TXTmaNV.getText());
        Date ngaydathang = Date.valueOf(TXTngayDat.getText());
        double giatien = Double.parseDouble(TXTgia.getText());
        int maKH = Integer.valueOf(TXTmaKH.getText());
        HoaDon hd = new HoaDon(maSP,tenSP,giatien,ngaydathang,maKH);
        if (hdDao.editHD(hd)==1) {
            JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
            fillTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa dữ liệu thất bại");
        } 
        }else{
            JOptionPane.showMessageDialog(this, "Vui long chon 1 hang de sua");
        }
    }
    
     public void deleteHD() {
        int maSP = Integer.parseInt(TXTmaHD.getText());
        int tenSP = Integer.parseInt(TXTmaNV.getText());
        Date ngaydathang = Date.valueOf(TXTngayDat.getText());
        double giatien = Double.parseDouble(TXTgia.getText());
        int maKH = Integer.valueOf(TXTmaKH.getText());
         HoaDon hd = new HoaDon(maSP,tenSP,giatien,ngaydathang,maKH);

        if (hdDao.deleteHD(hd)==1) {
            fillTable();
            JOptionPane.showMessageDialog(this, "Xóa sản phẩm mới thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBdonHang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TXTmaHD = new javax.swing.JTextField();
        TXTmaNV = new javax.swing.JTextField();
        TXTngayDat = new javax.swing.JTextField();
        TXTgia = new javax.swing.JTextField();
        BTaddDH = new javax.swing.JButton();
        BTupdateDH = new javax.swing.JButton();
        BTdeleteDH = new javax.swing.JButton();
        TXTmaKH = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Quản lý hóa đơn");

        jLabel2.setText("Mã hóa đơn:");

        jLabel3.setText("Mã nhân viên");

        jLabel4.setText("Ngày đặt");

        jLabel5.setText("Đơn giá:");

        TBdonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBdonHang);

        jLabel6.setText("Mã khách hàng:");

        BTaddDH.setText("THÊM");
        BTaddDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTaddDHActionPerformed(evt);
            }
        });

        BTupdateDH.setText("SỬA");
        BTupdateDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTupdateDHActionPerformed(evt);
            }
        });

        BTdeleteDH.setText("XÓA");
        BTdeleteDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTdeleteDHActionPerformed(evt);
            }
        });

        TXTmaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTmaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTmaHD)
                            .addComponent(TXTmaNV)
                            .addComponent(TXTngayDat)
                            .addComponent(TXTgia, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(TXTmaKH))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTdeleteDH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(BTupdateDH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTaddDH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXTmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(TXTmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(TXTngayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TXTgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(BTaddDH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTupdateDH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BTdeleteDH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TXTmaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTmaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTmaKHActionPerformed

    private void BTaddDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTaddDHActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_BTaddDHActionPerformed

    private void BTupdateDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTupdateDHActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_BTupdateDHActionPerformed

    private void BTdeleteDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTdeleteDHActionPerformed
        // TODO add your handling code here:
        deleteHD();
    }//GEN-LAST:event_BTdeleteDHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTaddDH;
    private javax.swing.JButton BTdeleteDH;
    private javax.swing.JButton BTupdateDH;
    private javax.swing.JTable TBdonHang;
    private javax.swing.JTextField TXTgia;
    private javax.swing.JTextField TXTmaHD;
    private javax.swing.JTextField TXTmaKH;
    private javax.swing.JTextField TXTmaNV;
    private javax.swing.JTextField TXTngayDat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
