/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.SanPhamChiTietDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;


/**
 *
 * @author ACER
 */
public class SanPhamChiTietVIEW extends javax.swing.JPanel {

    /**
     * Creates new form SanPhamChiTiet
     */
    DefaultTableModel tableModel;
    SanPhamChiTietDAO spctDAO = new SanPhamChiTietDAO();

    /**
     * Creates new form QLNLpanel
     */
    public SanPhamChiTietVIEW() {
        initComponents();
    }

    public void initTable() {
        String[] cols = new String[]{"Mã SPCT", "Tên SP", "Size", "Mã Topping"};
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(cols);
        TBsanPhamChiTiet.setModel(tableModel);
    }


    private boolean validateForm() {
        if (TXTmaSPCT.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã SPCT.");
            return false;
        }
        if (TXTmaSP.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ma SP.");
            return false;
        }
        if (TXTsize.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Size.");
            return false;
        }        
        if (TXTmaToping.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã Topping.");
            return false;
        }   
        return true;
    }
    
    public void add(){
        int maSPCT = Integer.parseInt(TXTmaSPCT.getText());
        int maSP = Integer.parseInt(TXTmaSP.getText());
        String size = TXTsize.getText();
        int maTopping = Integer.parseInt(TXTmaToping.getText());
        SanPhamChiTiet spct = new SanPhamChiTiet(maSPCT, maSP, size, maTopping);
        if (spctDAO.addNL(spct)==1) {
            JOptionPane.showMessageDialog(this, "Nhap thanh cong");
        }else{
            JOptionPane.showMessageDialog(this, "Loi!");
        } 
    }
    
    public void Update() {
        int i = TBsanPhamChiTiet.getSelectedRow();
        if (i != -1) { 
        int maSPCT = Integer.parseInt(TXTmaSPCT.getText());
        int maSP = Integer.parseInt(TXTmaSP.getText());
        String size = TXTsize.getText();
        int maTopping = Integer.parseInt(TXTmaToping.getText());
         SanPhamChiTiet spct = new SanPhamChiTiet(maSPCT, maSP, size, maTopping);
        if (spctDAO.editNL(spct)==1) {
            JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Sửa dữ liệu thất bại");
        } 
        }else{
            JOptionPane.showMessageDialog(this, "Vui long chon 1 hang de sua");
        }
    }
    
     public void deleteSPCT() {
       int maSPCT = Integer.parseInt(TXTmaSPCT.getText());
        int maSP = Integer.parseInt(TXTmaSP.getText());
        String size = TXTsize.getText();
        int maTopping = Integer.parseInt(TXTmaToping.getText());
          SanPhamChiTiet spct = new SanPhamChiTiet(maSPCT, maSP, size, maTopping);

        if (spctDAO.deleteNL(spct)==1) {
            JOptionPane.showMessageDialog(this, "Xóa sản phẩm mới thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBsanPhamChiTiet = new javax.swing.JTable();
        TXTmaSPCT = new javax.swing.JTextField();
        TXTmaSP = new javax.swing.JTextField();
        TXTsize = new javax.swing.JTextField();
        TXTmaToping = new javax.swing.JTextField();
        BTaddSPCT = new javax.swing.JButton();
        BTeditSPCT = new javax.swing.JButton();
        BTdeleteSPCT = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Sản phẩm chi tiết");

        jLabel2.setText("Mã sản phẩm chi tiết:");

        jLabel3.setText("Mã sản phẩm:");

        jLabel4.setText("Size:");

        jLabel5.setText("Mã Toping:");

        TBsanPhamChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBsanPhamChiTiet);

        BTaddSPCT.setText("THÊM");
        BTaddSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTaddSPCTActionPerformed(evt);
            }
        });

        BTeditSPCT.setText("SỬA");
        BTeditSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTeditSPCTActionPerformed(evt);
            }
        });

        BTdeleteSPCT.setText("XÓA");
        BTdeleteSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTdeleteSPCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTmaSPCT)
                                    .addComponent(TXTmaSP)
                                    .addComponent(TXTsize)
                                    .addComponent(TXTmaToping, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTeditSPCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTaddSPCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTdeleteSPCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTmaSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTaddSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTeditSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXTsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BTdeleteSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTmaToping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTaddSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTaddSPCTActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_BTaddSPCTActionPerformed

    private void BTeditSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTeditSPCTActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_BTeditSPCTActionPerformed

    private void BTdeleteSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTdeleteSPCTActionPerformed
        // TODO add your handling code here:
        deleteSPCT();
    }//GEN-LAST:event_BTdeleteSPCTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTaddSPCT;
    private javax.swing.JButton BTdeleteSPCT;
    private javax.swing.JButton BTeditSPCT;
    private javax.swing.JTable TBsanPhamChiTiet;
    private javax.swing.JTextField TXTmaSP;
    private javax.swing.JTextField TXTmaSPCT;
    private javax.swing.JTextField TXTmaToping;
    private javax.swing.JTextField TXTsize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
