/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;

/**
 *
 * @author ADMIN
 */
public class trangChuQuanLy_1 extends javax.swing.JFrame {

    /**
     * Creates new form trangChu
     */
    public trangChuQuanLy_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanelTCCN = new javax.swing.JPanel();
        btnqlnv = new javax.swing.JButton();
        btnqlsp = new javax.swing.JButton();
        btnQLDT = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnQLNL = new javax.swing.JButton();
        jPanelCN = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Documents = new javax.swing.JMenuItem();
        FileManager = new javax.swing.JMenuItem();
        FileExplorer = new javax.swing.JMenuItem();
        Resources = new javax.swing.JMenuItem();
        ImportsAndExports = new javax.swing.JMenuItem();
        DataFiles = new javax.swing.JMenuItem();
        Manager = new javax.swing.JMenu();
        ControlPanel = new javax.swing.JMenuItem();
        Administrator = new javax.swing.JMenuItem();
        Dashboard = new javax.swing.JMenuItem();
        ManagementCenter = new javax.swing.JMenuItem();
        SettingsManager = new javax.swing.JMenuItem();
        UserManagement = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        SupportCenter = new javax.swing.JMenuItem();
        HelpAndSupport = new javax.swing.JMenuItem();
        UserGuide = new javax.swing.JMenuItem();
        KnowledgeBase = new javax.swing.JMenuItem();
        FAQs = new javax.swing.JMenuItem();
        GettingStarted = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTCCN.setBorder(javax.swing.BorderFactory.createTitledBorder("Tùy Chọn Chức Năng"));

        btnqlnv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnqlnv.setText("Quản Lý Nhân Viên");
        btnqlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlnvActionPerformed(evt);
            }
        });

        btnqlsp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnqlsp.setText("Quản Lý Sản Phẩm");
        btnqlsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlspActionPerformed(evt);
            }
        });

        btnQLDT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLDT.setText("Quản Lý Doanh Thu");
        btnQLDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDTActionPerformed(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnQLNL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLNL.setText("Quản Lý Nguyên Liệu");
        btnQLNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTCCNLayout = new javax.swing.GroupLayout(jPanelTCCN);
        jPanelTCCN.setLayout(jPanelTCCNLayout);
        jPanelTCCNLayout.setHorizontalGroup(
            jPanelTCCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTCCNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTCCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQLDT, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnqlsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnQLNL, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
        );
        jPanelTCCNLayout.setVerticalGroup(
            jPanelTCCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTCCNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnqlsp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLNL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCN.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức Năng"));

        javax.swing.GroupLayout jPanelCNLayout = new javax.swing.GroupLayout(jPanelCN);
        jPanelCN.setLayout(jPanelCNLayout);
        jPanelCNLayout.setHorizontalGroup(
            jPanelCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        jPanelCNLayout.setVerticalGroup(
            jPanelCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        Documents.setText("Documents");
        jMenu1.add(Documents);

        FileManager.setText("File Manager");
        FileManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileManagerActionPerformed(evt);
            }
        });
        jMenu1.add(FileManager);

        FileExplorer.setText("File Explorer");
        jMenu1.add(FileExplorer);

        Resources.setText("Resources ");
        Resources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResourcesActionPerformed(evt);
            }
        });
        jMenu1.add(Resources);

        ImportsAndExports.setText("Imports/Exports");
        jMenu1.add(ImportsAndExports);

        DataFiles.setText("Data Files ");
        DataFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataFilesActionPerformed(evt);
            }
        });
        jMenu1.add(DataFiles);

        jMenuBar1.add(jMenu1);

        Manager.setText("Manager");

        ControlPanel.setText("Control Panel");
        Manager.add(ControlPanel);

        Administrator.setText("Administrator");
        Manager.add(Administrator);

        Dashboard.setText("Dashboard");
        Manager.add(Dashboard);

        ManagementCenter.setText("ManagementCenter ");
        Manager.add(ManagementCenter);

        SettingsManager.setText("Settings Manager");
        Manager.add(SettingsManager);

        UserManagement.setText("User Management ");
        UserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagementActionPerformed(evt);
            }
        });
        Manager.add(UserManagement);

        jMenuBar1.add(Manager);

        help.setText("Help");

        SupportCenter.setText("Support Center ");
        help.add(SupportCenter);

        HelpAndSupport.setText("Help & Support ");
        help.add(HelpAndSupport);

        UserGuide.setText("User Guide");
        UserGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserGuideActionPerformed(evt);
            }
        });
        help.add(UserGuide);

        KnowledgeBase.setText("Knowledge Base");
        KnowledgeBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnowledgeBaseActionPerformed(evt);
            }
        });
        help.add(KnowledgeBase);

        FAQs.setText("FAQs");
        help.add(FAQs);

        GettingStarted.setText("Getting Started");
        help.add(GettingStarted);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTCCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTCCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserGuideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserGuideActionPerformed

    private void KnowledgeBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnowledgeBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnowledgeBaseActionPerformed

    private void UserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserManagementActionPerformed

    private void FileManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileManagerActionPerformed

    private void ResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResourcesActionPerformed

    private void DataFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataFilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataFilesActionPerformed

    private void btnqlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlnvActionPerformed
        // TODO add your handling code here:
        NhanVien p1 = new NhanVien();
        p1.setSize(718, 427); // Hoặc bạn có thể bỏ qua setSize hoàn toàn
        p1.setLocation(0, 0);

        jPanelCN.removeAll();
        jPanelCN.setLayout(new BorderLayout());
        jPanelCN.add(p1, BorderLayout.CENTER);
        jPanelCN.revalidate();
        jPanelCN.repaint();
    }//GEN-LAST:event_btnqlnvActionPerformed

    private void btnqlspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlspActionPerformed
        // TODO add your handling code here:
        SanPham p1 = new SanPham();
        p1.setSize(718, 427); // Hoặc bạn có thể bỏ qua setSize hoàn toàn
        p1.setLocation(0, 0);

        jPanelCN.removeAll();
        jPanelCN.setLayout(new BorderLayout());
        jPanelCN.add(p1, BorderLayout.CENTER);
        jPanelCN.revalidate();
        jPanelCN.repaint();
    }//GEN-LAST:event_btnqlspActionPerformed

    private void btnQLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDTActionPerformed
        // TODO add your handling code here:
        DoanhThu p1 = new DoanhThu();
        p1.setSize(718, 427); // Hoặc bạn có thể bỏ qua setSize hoàn toàn
        p1.setLocation(0, 0);

        jPanelCN.removeAll();
        jPanelCN.setLayout(new BorderLayout());
        jPanelCN.add(p1, BorderLayout.CENTER);
        jPanelCN.revalidate();
        jPanelCN.repaint();
    }//GEN-LAST:event_btnQLDTActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnQLNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLNLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trangChuQuanLy_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trangChuQuanLy_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trangChuQuanLy_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trangChuQuanLy_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trangChuQuanLy_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Administrator;
    private javax.swing.JMenuItem ControlPanel;
    private javax.swing.JMenuItem Dashboard;
    private javax.swing.JMenuItem DataFiles;
    private javax.swing.JMenuItem Documents;
    private javax.swing.JMenuItem FAQs;
    private javax.swing.JMenuItem FileExplorer;
    private javax.swing.JMenuItem FileManager;
    private javax.swing.JMenuItem GettingStarted;
    private javax.swing.JMenuItem HelpAndSupport;
    private javax.swing.JMenuItem ImportsAndExports;
    private javax.swing.JMenuItem KnowledgeBase;
    private javax.swing.JMenuItem ManagementCenter;
    private javax.swing.JMenu Manager;
    private javax.swing.JMenuItem Resources;
    private javax.swing.JMenuItem SettingsManager;
    private javax.swing.JMenuItem SupportCenter;
    private javax.swing.JMenuItem UserGuide;
    private javax.swing.JMenuItem UserManagement;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLDT;
    private javax.swing.JButton btnQLNL;
    private javax.swing.JButton btnqlnv;
    private javax.swing.JButton btnqlsp;
    private javax.swing.JMenu help;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanelCN;
    private javax.swing.JPanel jPanelTCCN;
    // End of variables declaration//GEN-END:variables

}
